# Generated by Django 5.1.3 on 2024-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
