name: Update Database

# Configuración del cron para que se ejecute cada mes
on:
  schedule:
    - cron: '0 0 1 * *' # Ejecuta el workflow el primer día de cada mes a medianoche UTC

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Check out el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar comandos de Django
      - name: Run management commands
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          cd netflix
          python manage.py migrate
          python manage.py import_movies
          python manage.py import_tv_shows

